version: '3.8'

services:
  api:
    image: joaquinzuazo/n5_api:v1.0.0
    environment:
      - PYTHONPATH=/app/src
    container_name: n5_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.presentation.api.main:app --host 0.0.0.0 --port 8000"

  front:
    image: joaquinzuazo/n5_front:v1.0.0
    container_name: n5_front
    environment:
      - BACKEND_URL=http://api:8000
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
