version: '3.8'

services:
  api:
    image: joaquinzuazo/n5_api:v1.0.0
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.presentation.api.main:app --host 0.0.0.0 --port 8000"
